name: Publish

on:
  release: 
    types: [published]

jobs:
  publish_packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Configure Git
        run: |
         git config --global user.name "${{ github.actor }}"
         git config --global user.email "github-action-${{ github.actor }}@users.noreply.github.com"
      
      # TODO: Check if it updates package.json version
      # Alternative Option - run: npm version ${{ github.event.release.tag_name }}

      - name: Set package version
        run: npm run set-version
      - name: Publish to NPM
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
