name: Publish

on:
  release: 
    types: [published]

env: 
  NEW_VERSION: ${{ github.event.release.tag_name }}

jobs:
  publish_packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 2
          token: ${{ secrets.RELEASE_BOT_PAT }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Configure Git
        run: |
         git config --global user.name "ts-to-go_bot"
         git config --global user.email "github-action-ts-to-go_bot@users.noreply.github.com"
      
      - name: Set package version
        run: npm version ${{ env.NEW_VERSION }} --no-git-tag-version --workspaces

      # TODO: remove examples workspace from publish
      - name: Publish to NPM
        run: npm publish --access public --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit package.json changes
        run: |
          git add "**/package.json"
          git add "package-lock.json"
          git commit -m "chore: release ${{ env.NEW_VERSION }} [skip ci]"
          git push origin HEAD:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_PAT }}
