name: Publish

on:
  release: 
    types: [published]

env: 
  NEW_VERSION: ${{ github.event.release.tag_name }}

jobs:
  publish_packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Configure Git
        run: |
         git config --global user.name "${{ github.actor }}"
         git config --global user.email "github-action-${{ github.actor }}@users.noreply.github.com"
      
      - name: Set package version
        run: npm version --no-git-tag-version ${{ env.NEW_VERSION }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit package.json changes
        run: |
          git add "**/package.json"
          git commit -m "chore: release ${{ env.NEW_VERSION }} [skip-ci]"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
